FROM python:3.12-slim AS base

WORKDIR /app/src

COPY requirements.txt .
COPY .env .
COPY .flake8 .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .

FROM base AS app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

FROM base AS worker
CMD ["celery", "-A", "services.celery.celery_worker.celery_app", "worker", "--loglevel=info"]

FROM base AS beat
CMD ["celery", "-A", "services.celery.celery_worker.celery_app", "beat", "--loglevel=info"]
